@echo off
echo Cleaning up...

echo Stopping and removing development services and volumes...
docker-compose --env-file .env.development down -v

echo Stopping and removing production services and volumes...
docker-compose -f docker-compose.prod.yml --env-file .env.production down -v

echo Pruning Docker system...
docker system prune -f

echo Cleanup completed.